/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStateRouteImport } from './routes/api/state'
import { Route as ApiIntervalsActivitiesRouteImport } from './routes/api/intervals/activities'
import { Route as ApiIntervalsAuthorizeRouteImport } from './routes/api/intervals/authorize'
import { Route as ApiIntervalsCallbackRouteImport } from './routes/api/intervals/callback'
import { Route as ApiIntervalsEventsRouteImport } from './routes/api/intervals/events'
import { Route as ApiIntervalsStreamRouteImport } from './routes/api/intervals/stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStateRoute = ApiStateRouteImport.update({
  id: '/api/state',
  path: '/api/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntervalsActivitiesRoute = ApiIntervalsActivitiesRouteImport.update({
  id: '/api/intervals/activities',
  path: '/api/intervals/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntervalsAuthorizeRoute = ApiIntervalsAuthorizeRouteImport.update({
  id: '/api/intervals/authorize',
  path: '/api/intervals/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntervalsCallbackRoute = ApiIntervalsCallbackRouteImport.update({
  id: '/api/intervals/callback',
  path: '/api/intervals/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntervalsEventsRoute = ApiIntervalsEventsRouteImport.update({
  id: '/api/intervals/events',
  path: '/api/intervals/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntervalsStreamRoute = ApiIntervalsStreamRouteImport.update({
  id: '/api/intervals/stream',
  path: '/api/intervals/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/state': typeof ApiStateRoute
  '/api/intervals/activities': typeof ApiIntervalsActivitiesRoute
  '/api/intervals/authorize': typeof ApiIntervalsAuthorizeRoute
  '/api/intervals/callback': typeof ApiIntervalsCallbackRoute
  '/api/intervals/events': typeof ApiIntervalsEventsRoute
  '/api/intervals/stream': typeof ApiIntervalsStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/state': typeof ApiStateRoute
  '/api/intervals/activities': typeof ApiIntervalsActivitiesRoute
  '/api/intervals/authorize': typeof ApiIntervalsAuthorizeRoute
  '/api/intervals/callback': typeof ApiIntervalsCallbackRoute
  '/api/intervals/events': typeof ApiIntervalsEventsRoute
  '/api/intervals/stream': typeof ApiIntervalsStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/state': typeof ApiStateRoute
  '/api/intervals/activities': typeof ApiIntervalsActivitiesRoute
  '/api/intervals/authorize': typeof ApiIntervalsAuthorizeRoute
  '/api/intervals/callback': typeof ApiIntervalsCallbackRoute
  '/api/intervals/events': typeof ApiIntervalsEventsRoute
  '/api/intervals/stream': typeof ApiIntervalsStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/state'
    | '/api/intervals/activities'
    | '/api/intervals/authorize'
    | '/api/intervals/callback'
    | '/api/intervals/events'
    | '/api/intervals/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/state'
    | '/api/intervals/activities'
    | '/api/intervals/authorize'
    | '/api/intervals/callback'
    | '/api/intervals/events'
    | '/api/intervals/stream'
  id:
    | '__root__'
    | '/'
    | '/api/state'
    | '/api/intervals/activities'
    | '/api/intervals/authorize'
    | '/api/intervals/callback'
    | '/api/intervals/events'
    | '/api/intervals/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiStateRoute: typeof ApiStateRoute
  ApiIntervalsActivitiesRoute: typeof ApiIntervalsActivitiesRoute
  ApiIntervalsAuthorizeRoute: typeof ApiIntervalsAuthorizeRoute
  ApiIntervalsCallbackRoute: typeof ApiIntervalsCallbackRoute
  ApiIntervalsEventsRoute: typeof ApiIntervalsEventsRoute
  ApiIntervalsStreamRoute: typeof ApiIntervalsStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/state': {
      id: '/api/state'
      path: '/api/state'
      fullPath: '/api/state'
      preLoaderRoute: typeof ApiStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intervals/activities': {
      id: '/api/intervals/activities'
      path: '/api/intervals/activities'
      fullPath: '/api/intervals/activities'
      preLoaderRoute: typeof ApiIntervalsActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intervals/authorize': {
      id: '/api/intervals/authorize'
      path: '/api/intervals/authorize'
      fullPath: '/api/intervals/authorize'
      preLoaderRoute: typeof ApiIntervalsAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intervals/callback': {
      id: '/api/intervals/callback'
      path: '/api/intervals/callback'
      fullPath: '/api/intervals/callback'
      preLoaderRoute: typeof ApiIntervalsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intervals/events': {
      id: '/api/intervals/events'
      path: '/api/intervals/events'
      fullPath: '/api/intervals/events'
      preLoaderRoute: typeof ApiIntervalsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intervals/stream': {
      id: '/api/intervals/stream'
      path: '/api/intervals/stream'
      fullPath: '/api/intervals/stream'
      preLoaderRoute: typeof ApiIntervalsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiStateRoute: ApiStateRoute,
  ApiIntervalsActivitiesRoute: ApiIntervalsActivitiesRoute,
  ApiIntervalsAuthorizeRoute: ApiIntervalsAuthorizeRoute,
  ApiIntervalsCallbackRoute: ApiIntervalsCallbackRoute,
  ApiIntervalsEventsRoute: ApiIntervalsEventsRoute,
  ApiIntervalsStreamRoute: ApiIntervalsStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
