/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStateRouteImport } from './routes/api/state'
import { Route as ApiCorosActivitiesRouteImport } from './routes/api/coros/activities'
import { Route as ApiCorosEventsRouteImport } from './routes/api/coros/events'
import { Route as ApiCorosLoginRouteImport } from './routes/api/coros/login'
import { Route as ApiCorosStreamRouteImport } from './routes/api/coros/stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStateRoute = ApiStateRouteImport.update({
  id: '/api/state',
  path: '/api/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCorosActivitiesRoute = ApiCorosActivitiesRouteImport.update({
  id: '/api/coros/activities',
  path: '/api/coros/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCorosEventsRoute = ApiCorosEventsRouteImport.update({
  id: '/api/coros/events',
  path: '/api/coros/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCorosLoginRoute = ApiCorosLoginRouteImport.update({
  id: '/api/coros/login',
  path: '/api/coros/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCorosStreamRoute = ApiCorosStreamRouteImport.update({
  id: '/api/coros/stream',
  path: '/api/coros/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/state': typeof ApiStateRoute
  '/api/coros/activities': typeof ApiCorosActivitiesRoute
  '/api/coros/events': typeof ApiCorosEventsRoute
  '/api/coros/login': typeof ApiCorosLoginRoute
  '/api/coros/stream': typeof ApiCorosStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/state': typeof ApiStateRoute
  '/api/coros/activities': typeof ApiCorosActivitiesRoute
  '/api/coros/events': typeof ApiCorosEventsRoute
  '/api/coros/login': typeof ApiCorosLoginRoute
  '/api/coros/stream': typeof ApiCorosStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/state': typeof ApiStateRoute
  '/api/coros/activities': typeof ApiCorosActivitiesRoute
  '/api/coros/events': typeof ApiCorosEventsRoute
  '/api/coros/login': typeof ApiCorosLoginRoute
  '/api/coros/stream': typeof ApiCorosStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/state'
    | '/api/coros/activities'
    | '/api/coros/events'
    | '/api/coros/login'
    | '/api/coros/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/state'
    | '/api/coros/activities'
    | '/api/coros/events'
    | '/api/coros/login'
    | '/api/coros/stream'
  id:
    | '__root__'
    | '/'
    | '/api/state'
    | '/api/coros/activities'
    | '/api/coros/events'
    | '/api/coros/login'
    | '/api/coros/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiStateRoute: typeof ApiStateRoute
  ApiCorosActivitiesRoute: typeof ApiCorosActivitiesRoute
  ApiCorosEventsRoute: typeof ApiCorosEventsRoute
  ApiCorosLoginRoute: typeof ApiCorosLoginRoute
  ApiCorosStreamRoute: typeof ApiCorosStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/state': {
      id: '/api/state'
      path: '/api/state'
      fullPath: '/api/state'
      preLoaderRoute: typeof ApiStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coros/activities': {
      id: '/api/coros/activities'
      path: '/api/coros/activities'
      fullPath: '/api/coros/activities'
      preLoaderRoute: typeof ApiCorosActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coros/events': {
      id: '/api/coros/events'
      path: '/api/coros/events'
      fullPath: '/api/coros/events'
      preLoaderRoute: typeof ApiCorosEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coros/login': {
      id: '/api/coros/login'
      path: '/api/coros/login'
      fullPath: '/api/coros/login'
      preLoaderRoute: typeof ApiCorosLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coros/stream': {
      id: '/api/coros/stream'
      path: '/api/coros/stream'
      fullPath: '/api/coros/stream'
      preLoaderRoute: typeof ApiCorosStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiStateRoute: ApiStateRoute,
  ApiCorosActivitiesRoute: ApiCorosActivitiesRoute,
  ApiCorosEventsRoute: ApiCorosEventsRoute,
  ApiCorosLoginRoute: ApiCorosLoginRoute,
  ApiCorosStreamRoute: ApiCorosStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
